<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_003_Lab04</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9d9b2370-7b90-4f10-8e64-8f3bbdfe7e0d</testSuiteGuid>
   <testCaseLink>
      <guid>5b2fabe6-dc7a-4586-928f-add654370676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_003_LoginPassNull</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6267f7ef-80cf-4236-a424-6e64dd9bc5f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad551515-6c2a-4f84-b023-15b020a2de9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_005_LoginUserPassFail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>accb3c89-04a1-464f-81db-21e339c55434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6feba18-356c-4abd-a446-6271f4fbb617</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db7d22f3-e3a8-4224-bf2f-13cf025cefcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_001_LoginUserPassNull</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b97c9363-e8da-4e28-95c2-a95822c7d47a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_002_LoginPassFail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36eab0af-013d-48ca-b432-f41c7fb7f91b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd1f0b8-6a36-4a66-876d-4b4443623739</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52876e29-40cb-4127-bcbb-73cf6348495e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_004_LoginSuccesful</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c651daa-4a16-4c45-933d-c87750a24322</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0c9ba20-3419-441d-a129-10acf0f912be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
