<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_002_Lab02</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e7a6de99-cad2-439e-ad29-02e341cd0138</testSuiteGuid>
   <testCaseLink>
      <guid>c8fb8bf1-3a92-4cd6-a958-9aa67d826394</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_003_LoginPassNull</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6267f7ef-80cf-4236-a424-6e64dd9bc5f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d655ad7-e089-4288-b643-070aec4e12b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_005_LoginUserPassFail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>accb3c89-04a1-464f-81db-21e339c55434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6feba18-356c-4abd-a446-6271f4fbb617</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e94d7410-83ac-4052-a89b-66666a549113</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_001_LoginUserPassNull</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2f329780-b30e-41f1-bd37-9fa75fa9f6f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_002_LoginPassFail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36eab0af-013d-48ca-b432-f41c7fb7f91b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd1f0b8-6a36-4a66-876d-4b4443623739</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb2dee7f-6a0a-421a-8cfd-04214c3c4965</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_004_LoginSuccesful</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c651daa-4a16-4c45-933d-c87750a24322</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0c9ba20-3419-441d-a129-10acf0f912be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
